### ISSUE TITLE
Saved pseudodata is indexed incorrectly after data keywords

### ISSUE THREAD

**Issue by siranipour** [NNPDF/nnpdf#1022]
Not really sure what's going on here, so any help will be greatly appreciated:

```yaml
pdf: NNPDF31_nnlo_as_0118_DISonly_pseudodata
fit: NNPDF31_nnlo_as_0118_DISonly_pseudodata

experiments:
  from_: fit

use_cuts: fromfit

theoryid: 53

template_text: |
  {@foo@}

actions_:
  - report(main=True)
````

Where I have
```python
def foo(groups_covmat):
    from IPython import embed; embed()
```
From `master` this gives
```
In [7]: ('BCDMS', 'BCDMSD', 253) in groups_covmat.index                                                                                                                       
Out[7]: True  
```
and from `git checkout 3.4`

```python
def foo(experiments_covmat):
    from IPython import embed; embed()
```

gives

```
In [7]: ('BCDMS', 'BCDMSD', 253) in experiments_covmat.index                                                                                                                       
Out[7]: False  
```

looks like the cuts aren't being handled correctly?
