### ISSUE TITLE
Deprecated experiments warning prints twice

### ISSUE THREAD

**Issue by siranipour** [NNPDF/nnpdf#1208]
The following prints the log warning twice:

```python
def func(groups_data, fitcontext):
    pass
```

```yaml
fit: NNPDF31_nnlo_as_0118_DISonly

experiments:
  from_: fit

use_cuts: fromfit

theoryid: 53

actions_:
  - func
```

Probably from a complicated chain of config calling.
