### ISSUE TITLE
`custom_group` and chi2 table doesn't arrange correctly 

### ISSUE THREAD

**Issue by siranipour** [NNPDF/nnpdf#1351]
The following runcard 
```yaml
metadata_group: custom_group

fit: NNPDF31_nnlo_as_0118_DISonly

pdf:
  from_: fit

use_cuts: internal

dataset_inputs:
  - {dataset: NMCPD, frac: 0.5, custom_group: foo}
  - {dataset: NMC, frac: 0.5, custom_group: bar}
  - {dataset: SLACP, frac: 0.5, custom_group: foo}
  - {dataset: SLACD, frac: 0.5, custom_group: foo}

theoryid: 53

template_text: |
  {@groups_chi2_table@}

actions_:
  - report(main=True)
```
doesn't work as expected: output is here
https://vp.nnpdf.science/vNBX1kDXSgGoKgKLZhZInw==

Note that, for example, the `npoints` within each custom_group don't add up. It is possible to replicate by having a `dataset_input` with one custom group sandwiched between other `dataset_input`s having a different grouping
