### ISSUE TITLE
Inaccurate vertical axis label for plots displaying relative uncertainties

### ISSUE THREAD

**Issue by enocera** [NNPDF/nnpdf#1353]
A validphys runcard like this
```
meta:
  title: Test PDF relative uncertainties
  author: Emanuele R. Nocera
  keywords: NNPDF4.0 paper

pdfs:
    - {id: 210713-n3fit-001, label: "NNPDF4.0 (NNLO)"}
    - {id: NNPDF31_nnlo_as_0118, label: "NNPDF3.1 (NNLO)"}

Q: 100
basis: flavour
ymin: 0.00
ymax: 0.15
xmin: 0.00005
xmax: 0.7
scale: log
normalize_to: 1

template_text: |

    ## PDF relative uncertainties
    {@ plot_pdf_uncertainties @}
    
actions_:
    - report(main=True)
```
produces this output
https://vp.nnpdf.science/-obMr7s4QT6pPH-hPKLeJg==
I think that the label on the vertical axis is a little misleading: this is not the uncertainty normalised to the first PDF set in the list; this is the relative uncertainty for each PDF set in the list. Should we fix the label? cc @Zaharid
