### ISSUE TITLE
Is `internal_multiclosure_dataset_loader` used?

### ISSUE THREAD

**Issue by scarlehoff** [NNPDF/nnpdf#1486]
This is one of the functions which are problematic in #1475, I'm trying to find some test or runcard where this function is used in order to remove the call to libNNPDF but cannot find it.

I've tried rerunning some reports tagged as `multiclosure` in the server with no luck (for instance https://vp.nnpdf.science/ebphG4sgSEG2hVt2c5A41g==/)

If anyone has a runcard for it I'd appreciate if it is shared. Otherwise I guess we can just remove (or truly deprecate, with the import of NNPDF and the creation of the libNNPDF PDF inside of the function) that family of functions?

**Comment by tgiani** [comment]
might be related to the closure PRs MIchael opened I while ago. I ll try to look at this next week

**Comment by tgiani** [comment]
so one example where this function is used is in this report produced by Michael some time ago https://vp.nnpdf.science/qSAUPISAQ7qQeh0nL8hIOg==/. The corresponding runcard uses the function ```plot_data_central_diff_histogram```, which requires the function ```data_replica_and_central_diff``` which requires ```internal_multiclosure_data_loader```. These functionalities are implemented in the PR #1321

**Comment by tgiani** [comment]
and I think that ```internal_multiclosure_dataset_loader``` is used basically for all the functions implemented in ```multiclosure.py```, so it is required to compute all the closure test estimators

**Comment by scarlehoff** [comment]
But is the stuff in `multiclosure` used?

**Comment by tgiani** [comment]
it is used for everything concerning closure test estimators. Including results reported in the NNPDF4.0 paper I guess

**Comment by tgiani** [comment]
so I don' t think we want to remove these functions

**Comment by scarlehoff** [comment]
Strange. I tried running a few runcards and that function didn't seem to be used. Maybe I did something wrong, I can try again.

Or better yet, do you see an easy way to avoid the libNNPDF call there? (I.e., the call to pdf load)

**Comment by tgiani** [comment]
uhm maybe I m the one doing smt wrong. if you try for example to run this runcard in the master 
```
it: 210326-mw-001

theoryid: 200
use_cuts: internal
q2min: 3.49                        # Q2 minimum
w2min: 12.5                        # W2 minimum

dataset_inputs:
# ATLAS
- {dataset: DYE906R_dw_ite, frac: 0.75, cfac: [ACC,QCD]}
- { dataset: ATLASWZRAP11CF, frac: 0.75, cfac: [QCD] } # N

meta:
 author: TG
 keywords: [test]
 title: Test plot_data_fits_bias_variance

diag_ns:
 - diagonal_basis: True
 - diagonal_basis: False

template_text: |
 # Results with 25 fits

 ## Central diff histogram
 {@with diag_ns@}
 # Diagonal: {@diagonal_basis@}
 {@plot_data_fits_bias_variance@}
 {@endwith@}


fits:
- 210326-mw-001
- 210326-mw-002

actions_:
 - report(main=True)

```
if you remove the function ```internal_multiclosure_dataset_loader``` from ```multiclosure.py``` you should get an error no?
