### ISSUE TITLE
`collect` resolves `explicit_node` lazily

### ISSUE THREAD

**Issue by siranipour** [NNPDF/nnpdf#1493]
This is probably more appropriate for [reportengine](https://github.com/NNPDF/reportengine), but the issue arises in validphys. Consider the following runcard:
```yaml
dataspecs:
  - pdf: NNPDF31_nnlo_as_0118

theoryid: 200

use_cuts: "internal"

dataset_input: {dataset: NMC}

actions_:
  - plot_fancy_dataspecs
```
This errors complaining that `covmat` is not an array. Taking a look, it's an `explicit_node` instance. If we look at why, it's because `plot_fancy_dataspecs` takes as an argument `dataspecs_results` which is a collection of `results` over `dataspecs`:
https://github.com/NNPDF/nnpdf/blob/73058484af2b857523821e59ae62f0a48406e401/validphys2/src/validphys/results.py#L1225
and since https://github.com/NNPDF/nnpdf/pull/1477 was merged, the `covariance_matrix` is dispatched as an `explicit_node` and this is the root of the bug. The `explicit_node` does not get resolved in time by reportengine and so the `results` objects in the collection don't have the `covariance_matrix` resolved by the time we hit this line:
https://github.com/NNPDF/nnpdf/blob/73058484af2b857523821e59ae62f0a48406e401/validphys2/src/validphys/dataplots.py#L476

**Comment by siranipour** [comment]
Although, I've just tried running this runcard using the `4.0.0` tag and the same thing happens. But even back then, the covariance matrix was an `explicit_node`. Has this always been an issue and I'm just using `dataspecs` incorrectly?

**Comment by Zaharid** [comment]
I am confused. Funnily enough this works

```python
def patata(covariance_matrix):
    log.error(covariance_matrix)
    return None

x = collect("patata", ("dataspecs",))
```

```yaml
dataspecs:
  - pdf: NNPDF31_nnlo_as_0118

theoryid: 200

use_cuts: "internal"

dataset_input: {dataset: NMC}

actions_:
  - x
```
