### ISSUE TITLE
x-axis not sorted in `plot_fancy`

### ISSUE THREAD

**Issue by siranipour** [NNPDF/nnpdf#1508]
Currently if I run a data theory comparison I get some odd behaviour, whereby there is a zig zagging behaviour:
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/43517072/151703602-253940c0-aa3e-4d53-aa92-4aaba2555e41.png">
it seems like the x-axis isn't sorted in a strictly increasing order. Any ideas what's happened here? I suppose we could simply remove the lines connecting the dots?

mwe:

```yaml
fit: 201118-si-002

pdfs:
  - id: NNPDF31_nnlo_as_0118
    label: str
  - id: 201118-si-002
    label: base

normalize_to: data

use_cuts: fromfit

theoryid: 53

dataset_input: {dataset: NTVNUDMNFe, frac: 0.5, cfac: [MAS]}

template_text: |
  {@plot_fancy@}

actions_:
  - report(main=True)

```
