### ISSUE TITLE
mc2hessian action doesn't write the correct error type

### ISSUE THREAD

**Issue by Zaharid** [NNPDF/nnpdf#1550]
The following runcard

```yaml
pdf: NNPDF31_nnlo_as_0118_1000
Q: 100
Neig: 25

mc2hname: "nnpdf_31_nnlo_hessian_25"

installgrid: True

actions_:
    - mc2hessian
```

should write `ErrorType: symmhessian` in the info file.

Instead if I look at it

```
$ 
cat nnpdf_31_nnlo_hessian_25.info  | grep ErrorType
ErrorType: replicas
```
