### ISSUE TITLE
Query: chi^2 comparison wrt scattered real data

### ISSUE THREAD

**Issue by LucianHL** [NNPDF/nnpdf#1584]
Can I ask if there is a straightforward way of using the validphys interface to evaluate a chi^2 comparison for a given input theory, but against real data after it has been smeared in the usual way, i.e. the usual pseudodata as is done in the fit to generate replicas? 

I can see that there are ways to produce such pseudodata: running a fit with 'savepseudodata' set to true in a fit for example, but this is then in a format from which it is not obvious to me how one could then evaluate a chi^2 via the off-the-shelf tools (abs_chi2_data, perreplica_chi2_table etc), where one specifies the input data via the 'ATLASTTBARTOT' labels etc. Running API.art_rep_generation(...) also seems to work, but again it is not clear to me how I can straightforwardly get a chi^2 from that.

Anyway, many thanks for making this code public, and in advance for your help!

Lucian

**Comment by scarlehoff** [comment]
Hi Lucian,

The problem of most of those tools dedicated to evaluate the `chi2` is that they assume one single target for the central value while you need one per replica (its own pseudodata). If I understood you correctly what you want might be provided by the following function: https://github.com/NNPDF/nnpdf/blob/1a191aaddd603f8b58196f0225918bcbe8fd0d06/validphys2/src/validphys/paramfits/dataops.py#L74.

You can get a dataframe that you can manipulate from here instead
https://github.com/NNPDF/nnpdf/blob/1a191aaddd603f8b58196f0225918bcbe8fd0d06/validphys2/src/validphys/chi2grids.py#L26

example runcard:

```yaml
meta:
  title: chi2 for replicas using pseudodata
  author: juacrumar
  keywords: [chi2, number of replicas, pseudodata]

fits:
  - pseudodata_test_fit_n3fit_220208

pdf: pseudodata_test_fit_n3fit_220208

dataset_inputs:
  from_: fit
theory:
  from_: fit
theoryid:
  from_: theory
mcseed:
  from_: fit
genrep:
  from_: fit

datacuts:
  from_: fit
use_cuts: fromfit
use_t0: true
t0pdfset:
  from_: datacuts

template_text: |
  {@ fits_matched_pseudoreplicas_chi2_table @}
actions_:
- report(main=True)

data_grouping_recorded_spec_:
  standard_report: dataset_label
```

(@RoyStegeman and @Zaharid might have further insight since I believe this is a feature I think they might use more often than I do )

**Comment by LucianHL** [comment]
Great, thank you - I will have a go at that!

**Comment by Zaharid** [comment]
I don't believe we have anything for this but should be easy enough to do. For example:

```python
import numpy as np

from validphys.calcutils import calc_chi2
from validphys.covmats import sqrt_covmat
from validphys.api import API

inp = dict(
    dataset_inputs=[{"dataset": "NMC"}, {"dataset": "NMCPD"}],
    use_cuts="internal",
    theoryid=200,
    replica=1,
    mcseed=123,
    genrep=True,
)

pseudodata = API.make_replica(**inp)
cds = API.groups_dataset_inputs_loaded_cd_with_cuts(**inp)
central = np.concatenate([cd.central_values for cd in cds])
covmat = API.dataset_inputs_covmat_from_systematics(**inp)
print(calc_chi2(sqrt_covmat(covmat), central - pseudodata) / len(central))
```

Or packaged as an extra module so it works with a runcard:

```python
# lucian.py
import numpy as np

from validphys.calcutils import calc_chi2
from validphys.covmats import sqrt_covmat



def print_pseudodata_chi2(
    make_replica,
    groups_dataset_inputs_loaded_cd_with_cuts,
    dataset_inputs_covmat_from_systematics,
):
    pseudodata = make_replica
    cds = groups_dataset_inputs_loaded_cd_with_cuts
    central = np.concatenate([cd.central_values for cd in cds])
    covmat = dataset_inputs_covmat_from_systematics

    res = calc_chi2(sqrt_covmat(covmat), central - pseudodata) / len(central)
    print(res)
    return res
```
which works with a runcard like

```yaml
# inp.yaml
dataset_inputs:
  - {dataset: "NMC"}
  - {dataset: "NMCPD"}

use_cuts: "internal"

theoryid: 200

replica: 1

mcseed: 123

genrep: True

actions_:
  - print_pseudodata_chi2
```

like 

```
$ validphys  inp.yaml -x lucian.py                            (nnpdfdev) 
[INFO]: All requirements processed and checked successfully. Executing actions.
0.9774475125611324
```

Some care needs to be taken in deciding which covmat to use. For example if you are interested in the t0 prescription (that we use for fitting) you should use `dataset_inputs_t0_covmat_from_systematics` as an input provider for the covmat, and supply a t0pdfset input, like `t0pdfset: NNPDF40_nnlo_as_01180`
