### ISSUE TITLE
Problem resolving explicit nodes

### ISSUE THREAD

**Issue by scarlehoff** [NNPDF/nnpdf#1925]
There's a few problems when resolving the explicit node of the covmat.

Some of these which involved the theory covmat have already been identified and will be solved in #1910 but some remain:

```yaml
meta:
    title: Example of bug
    keywords: [example]

pdfs:
    - id: NNPDF40_nnlo_lowprecision

theoryid: 162

use_cuts: "internal"

dataset_inputs:
      - { dataset: BCDMSP}

template_text: |
  {@ dataset_inputs::pdfs plot_fancy(normalize_to=data)@}

actions_:
  - report(main=true)
```

(the strange thing is that if I add `{@ dataset_inputs plot_fancy @}` in the `template_text`, the runcard works.

I don't know since when this bug has been around, but it is not new. I can reproduce it also with code from 2020 (nnpdf tag 4.0.0 and reportengine 0.29).
