### ISSUE TITLE
Distance plots incorrectly allow not specifying a reference

### ISSUE THREAD

**Issue by Zaharid** [NNPDF/nnpdf#214]
The following runcard:

```yaml
pdfs:
    - NNPDF31_nlo_as_0118_hessian
    - NNPDF31_nnlo_as_0118_hessian

normalize_to: null

Q: 10

actions_:
    - plot_pdfdistances
```

incorrectly passes the checks, and then produces a runtime error because we are normalizing to `None`.

I think it would be sufficient to change the parameters of `normalize_to` to not allow for `typeof(None)`.
