### ISSUE TITLE
Having trouble with datasets 

### ISSUE THREAD

**Issue by RosalynLP** [NNPDF/nnpdf#258]
Hi, I am running into difficulties when I am trying to load into validphys two different theories with corresponding PDFs: for NNPDF3.1 NLO and NNPDF3.1 NNLO, so that I can compute a shift vector.

My runcard looks like:
```
theoryids:
   - 52
   - 53

dataspecs:
        - theoryid: 52
          pdf: NNPDF31_nlo_as_0118_1000
          speclabel: "NNPDF3.1 NLO central"
          fit: NNPDF31_nlo_as_0118_1000
        - theoryid: 53
          pdf: NNPDF31_nnlo_as_0118_1000
          speclabel: "NNPDF3.1 NNLO central"
          fit: NNPDF31_nnlo_as_0118_1000

normalize_to: 1

use_cuts: True
#fit: 180421-lr-nlo-central_global

#pdf:
#  from_: fit

experiments:
# Fixed target DIS
  - experiment: NMC
    datasets:
      - dataset: NMCPD
      - dataset: NMC
  - experiment: SLAC
    datasets:
      - dataset: SLACP
      - dataset: SLACD
  - experiment: BCDMS
    datasets:
      - dataset: BCDMSP
      - dataset: BCDMSD
  - experiment: CHORUS
    datasets:
      - dataset: CHORUSNU
      - dataset: CHORUSNB
  - experiment: NTVDMN
    datasets:
      - dataset: NTVNUDMN
      - dataset: NTVNBDMN
# HERA data
  - experiment: HERACOMB
    datasets:
      - dataset: HERACOMBNCEM 
      - dataset: HERACOMBNCEP460
      - dataset: HERACOMBNCEP575
      - dataset: HERACOMBNCEP820
      - dataset: HERACOMBNCEP920
      - dataset: HERACOMBCCEM 
      - dataset: HERACOMBCCEP 
# Combined HERA charm production cross-sections
  - experiment: HERAF2CHARM
    datasets:
      - dataset: HERAF2CHARM
# F2bottom data
  - experiment: F2BOTTOM
    datasets: 
      - dataset: H1HERAF2B
      - dataset: ZEUSHERAF2B
  - experiment: D0
    datasets:
      - dataset: D0ZRAP
      - dataset: D0WEASY
      - dataset: D0WMASY
  - experiment: ATLAS
    datasets:
      - dataset: ATLASWZRAP36PB
      - dataset: ATLASZHIGHMASS49FB
      - dataset: ATLASLOMASSDY11EXT
      - dataset: ATLASWZRAP11
      - dataset: ATLAS1JET11
      - dataset: ATLASZPT8TEVMDIST
      - dataset: ATLASZPT8TEVYDIST
      - dataset: ATLASTTBARTOT
      - dataset: ATLASTOPDIFF8TEVTRAPNORM
  - experiment: CMS
    datasets:
      - dataset: CMSWEASY840PB
      - dataset: CMSWMASY47FB
      - dataset: CMSWCHARMRAT
      - dataset: CMSDY2D11
      - dataset: CMSWMU8TEV
      - dataset: CMSJETS11
      - dataset: CMSTTBARTOT
      - dataset: CMSTOPDIFF8TEVTTRAPNORM
  - experiment: CDF
    datasets:
      - dataset: CDFZRAP
      - dataset: CDFR2KT
  - experiment: LHCb
    datasets:
      - dataset: LHCBZ940PB
      - dataset: LHCBZEE2FB

template_text: |
   {@with matched_datasets_from_dataspecs@}

   {@evalue@}

   {@endwith@}

actions_:
  - report(main=true)
```
but I get an error because it's looking for a specific dataset, although I don't see where I asked it to:

`[ERROR]: Failed processing key 'experiments' at line 31, position 1.
[ERROR]: Bad configuration encountered:
Bad filter configuration. Could not find: /Disk/ds-sopa-personal/s1303034/NNPDF/results/NNPDF31_nnlo_as_0118_1000/filter/CMSWCHARMRAT`

Any ideas where I am going wrong with this? I tried to follow a similar layout to an example in the vp2 guide.
