### ISSUE TITLE
Fivetheories key error

### ISSUE THREAD

**Issue by voisey** [NNPDF/nnpdf#326]
When I run a simple runcard on master to produce the the 3-point theory covariance matrix I get KeyError: 'fivetheories', even though fivetheories appears to be set to None by default. The runcard I am using is below. Any idea what's going wrong?

```
meta:
   author: Cameron Voisey
   keywords: [theory uncertainties, scale variations]
   title: NLO 3-point variations

default_theory:
   - theoryid: 163

theoryids:
   - 163
   - 180
   - 173

use_cuts: fromfit
fit: 180421-lr-nlo-central_global

pdf:
  from_: fit

experiments:
  - experiment: NMC
    datasets:
      - dataset: NMCPD
      - dataset: NMC
  - experiment: ATLAS
    datasets:
      - dataset: ATLASWZRAP36PB
      - dataset: ATLASZHIGHMASS49FB
      - dataset: ATLASLOMASSDY11EXT
      - dataset: ATLASWZRAP11
      - dataset: ATLAS1JET11
      - dataset: ATLASZPT8TEVMDIST
      - dataset: ATLASZPT8TEVYDIST
      - dataset: ATLASTTBARTOT
      - dataset: ATLASTOPDIFF8TEVTRAPNORM

actions_:
  - default_theory theory_covmat
```
