### ISSUE TITLE
Adding PDF uncertainty in validphys

### ISSUE THREAD

**Issue by mariaubiali** [NNPDF/nnpdf#446]
I would like to get theoretical predictions & its PDF uncertainty from a given FK table. I have nearly managed to do that by running the script I paste below. However, I get predictions from individual replicas. Would it be possible to add a function that gives 68% CL uncertainty band?

```yaml
fit: pheno
use_cuts: "fromfit"

experiments:
    - experiment: ATLAS
      datasets:
          - dataset: ATLASWZTOT13TEV81PB

dataspecs:
    - theoryid: 163
      pdf: 181126-si-nlo-central_DISonly

    - theoryid: 163
      pdf: 190326-ern-nlo-DIS

template_text: |
    % (exp) vs (exp+th) comparison for
      {@dataspecs experiment_result_table@}

actions_:
  - report(main=True)
```

Thank you!
Maria
