### ISSUE TITLE
Make a higher level "chi2 table" like API

### ISSUE THREAD

**Issue by wilsonmr** [NNPDF/nnpdf#610]
So many of the tables in `results` and now `closure` are small variations on a theme. I was wondering if we could shorten the code a bit by making some kind of table API which allows tables to be declared in runcard somehow

```yaml
tablespec:
  index: {'experiments': 'datasets'}
  columns: {`fits`: {`ndata`, `central`}}
  show_total: True

actions_:
 - chi2_table_action
```
maybe we could even be more adventurous and have cross compatibility for anything which can be tabled in this way:

```yaml
tablespec:
  index: {'experiments': 'datasets'}
  columns: {'fits': {'ndata', {'chi2': 'central'}}}
  show_total: True

actions_:
 - generic_table_action
```

Not sure if that would even be useful however.. Probably the first thing would be sufficient to start

I haven't thought that through really but I think it could work? I'm sure @Zaharid already mentioned it in #447 

specifically: https://github.com/NNPDF/nnpdf/pull/447#issuecomment-493934624
