### ISSUE TITLE
Produce scale variation dataspecs

### ISSUE THREAD

**Issue by voisey** [NNPDF/nnpdf#750]
I would like to have a production rule that given a central `theoryid` and `point_prescription` produces a `dataspecs` such as the one on line 15 of the first example here https://docs.nnpdf.science/vp/theorycov/examples.html, as this would eliminate one more annoying thing that the user has to specify in a runcard that uses the theory covmat. I've just written something that does this (it's essentially just an extension of https://github.com/NNPDF/nnpdf/pull/664) and it works fine. I can therefore just do something like the following in the runcard:
```
dataspecs:
  from_: scale_variation_dataspecs
```
However, I would also like it to work for the validation runcard here: https://docs.nnpdf.science/vp/theorycov/examples.html#validation-report. There we have something like:
```
dataspecs:
       - theoryid: 163
          speclabel: $(\xi_F,\xi_R)=(1,1)$
          experiments: *experiments_list_nlo
       - theoryid: 177
          speclabel: $(\xi_F,\xi_R)=(2,1)$
          experiments: *experiments_list_nlo
       - theoryid: 176
          speclabel: $(\xi_F,\xi_R)=(0.5,1)$
          experiments: *experiments_list_nlo
       - theoryid: 179
          speclabel: $(\xi_F,\xi_R)=(1,2)$
          experiments: *experiments_list_nlo
       - theoryid: 174
          speclabel: $(\xi_F,\xi_R)=(1,0.5)$
          experiments: *experiments_list_nlo
```
so what I did for the first case doesn't work, because `dataspecs` also includes `experiments`. Is there some way that we could not write the `experiments` in the `dataspecs`, so that the `dataspecs` is simpler, and looks like it does in the first case?
